import os
from dotenv import load_dotenv
from dataclasses import dataclass

from langchain.tools import tool, ToolRuntime
from langchain_openai import ChatOpenAI
from langchain.agents import create_agent
from langgraph.checkpoint.memory import InMemorySaver
from langchain.agents.structured_output import ToolStrategy

from symptoms_RAG import setup_rag_components
from prompts.tech_prompts import diagnose_prompt

# Load environment variables
load_dotenv()
API_KEY = os.getenv("OPENAI_API_KEY")


# --------------------------
# SYSTEM PROMPT
# --------------------------
SYSTEM_PROMPT = """
You are a helpful assistant with knowledge on jet aircraft maintenance.

You have access to two tools:

- symptoms_rag: use this to diagnose symptoms of aircraft problems or failures.
- find_tasks: use this to find and list all the maintenance tasks for the aircraft systems or components provided.

Your only task is to decide which tool to use based on your knowledge and the question.
Once the tool gives an answer, present it to the user as it was generated by the tool, 
without further formatting or thinking.
If you cannot determine which tool to use, respond with 'I cannot answer your question,
please clarify'.
"""
# Use the answer from the tools as it is, without further formatting or thinking.

# --------------------------
# Context Schema
# --------------------------
@dataclass
class Context:
    user_id: str

#-------------------------------
# Define response format
#------------------------------
@dataclass
class ResponseFormat:
    """Response schema for the agent."""
    # A response from the RAG tools (always required)
    rag_response: str
    # list of systems or components if available in the response
    systems_components: str | None = None


# --------------------------
# Tools definitions
#---------------------------

# Find tasks RAG tool
@tool
def find_tasks(components: str) -> str:
    """ finds tasks for systems or components responsible for the failure."""
    return f"Tasks found:  {components}"


# DIAGNOSTICS from symptoms RAG tool
@tool
def symptoms_rag(symptoms_user: str) -> str:
    """
    Ask user for symptoms to determine the cause of problem.
    """
    # Offline
    retriever, model_rag = setup_rag_components()

    # Online

    user_question = symptoms_user
    # input("\nPlease briefly describe the symptoms of the failure or problem: ")
    if user_question.lower() == "none":
        return "Thank you for using AI_AMTMan.\nHasta la vista baby...!"

    print("Thinking...")

    # 1. Retrieve
    retrieved_docs = retriever.invoke(user_question)
    context = "\n\n".join([doc.page_content for doc in retrieved_docs])

    # 2. Augment
    prompt_template = diagnose_prompt(user_question, context)

    # 3. Generate
    rag_response = model_rag.invoke(prompt_template)

    return f"\nAnswer:\n, {rag_response.content}"



# --------------------------
# AI Model parameter definition
# --------------------------
model = ChatOpenAI(
    api_key=API_KEY,
    temperature=0,
    model="gpt-5-mini",
    reasoning_effort="low"
)


# --------------------------
# MEMORY
# --------------------------
checkpointer = InMemorySaver()


# --------------------------
# AGENT
# --------------------------
agent = create_agent(
    model=model,
    system_prompt=SYSTEM_PROMPT,
    tools=[find_tasks, symptoms_rag],
    context_schema=Context,
    response_format=ToolStrategy(ResponseFormat),
    checkpointer=checkpointer
)

config = {"configurable": {"thread_id": "1"}}


# --------------------------
# MAIN LOOP
# --------------------------
while True:
    maintenance_query = input("\nHow can I help you today?: ")
    print(f"\nChoosing tool...")

    if maintenance_query.lower() == "none":
        print("No question... Goodbye!")
        break

    response = agent.invoke(
        {"messages": [{"role": "user", "content": maintenance_query}]},
        config=config,
        context=Context(user_id="1")
    )

    # Print only the assistant final message
    print("\nAssistant:", response["structured_response"].rag_response)
    print("\n",response["structured_response"].systems_components)

